### PR TITLE
SVS orientation v1 

### PR DESCRIPTION
**Pull request by NeutralKaon**
I am not sure at all that I've got the orientation right in general but this seems like a reasonable first pass…

### CODE REVIEW

**Comment by NeutralKaon** [comment]
Also – the checks fail because the data repo is pinned to the wrong version – apologies if that is my fault…

**Comment by wexeee** [comment]
Yes, it seems that the submodule version has changed. Could you try to sort that before I merge this? I think that if you git pull in the submodule you will get the mode recent version (which should be right). Then commit that back here. It should point to 5a861e.

**Comment by NeutralKaon** [comment]
I think that `git checkout 5a861eb5466f5e06252e2439e892b52452ee5b36` in the submodule directory fixed this – sorry.

**Comment by NeutralKaon** [comment]
Sod that linter.

**Pull request merged**
